branches:
  only:
    - master

skip_tags: true

version: '{branch}-{build}'

image: Visual Studio 2019

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: 'true'
  dist_name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_NUMBER)
  dist_exclude: |
    *.a
    *.pyc
    *.pyo
    mingw32/include
    mingw32/lib/cv2
    mingw32/lib/python*/test
    mingw32/share/doc
    mingw32/share/gtk-doc
    mingw32/share/man
    mingw32/share/OpenCV
    mingw32/share/opencv*
    usr/share/doc
    usr/share/locale
    usr/share/man
    usr/share/vim

clone_depth: 1

cache: C:\msys64\var\cache\pacman\pkg

init:
  - cmd: |
      REM When calling this, you must use --login (required by MSYS2)
      set bash=C:\msys64\usr\bin\bash.exe

      REM Show detailed package statistics on pacman -S
      echo [options]>> C:\msys64\etc\pacman.conf
      echo VerbosePkgLists>> C:\msys64\etc\pacman.conf

install:
  - cmd: |
      %bash% -lc "pacman --noconfirm --noprogressbar -Syuu"
      cd C:\msys64\home\appveyor
      git clone --depth=1 https://github.com/exaile/python-gtk3-gst-sdk.git
      git clone --depth=1 https://github.com/exaile/exaile.git

build_script:
  - cmd: |
      set GTK_SDK_VERBOSE=1
      %bash% -lc "cd exaile/tools/installer && ../../../python-gtk3-gst-sdk/win_installer/build_win32_sdk.sh"
      %bash% -lc "cd exaile/tools/installer && source project.config && pacman --root ""$PWD/_build_root"" --noconfirm -S --needed $TARGET_DOWNLOAD_PKGS"
      %bash% -lc "cd exaile/tools/installer/_build_root && time tar -cf ../sdk.tar.zst -I 'zstd -17 -T0' -X <(echo ""$dist_exclude"") * && ls -sh ../sdk.tar.zst"

after_build:
  - cmd: move exaile\tools\installer\sdk.tar.zst "%APPVEYOR_BUILD_FOLDER%\%dist_name%.tar.zst"

artifacts:
  - path: $(dist_name).tar.zst
    name: dist

deploy:
  provider: GitHub
  release: $(dist_name)
  description: ''
  auth_token:
    secure: SIgbVNCx4ge9VT0J/0X8kovjreWVKJyWiquTLXmoUZItQk5aNr5jl1KNbOiTPdeu # exailebot's access token
  artifact: dist

after_deploy:
  - cmd: |
      %bash% -lc "pacman --root ""$PWD/exaile/tools/installer/_build_root"" --noconfirm --noprogressbar -Sc"
